### ISSUE TITLE
Set this text to come from the props instead of hardcoding it inside the component

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#11]
https://github.com/Sephirosu/figma-next-tailwind/blob/5c2265816c9ba4c67ab547a2f2959df413e0d4d8/src/components/Navbar/PromoMessage.tsx#L4

**Comment by Sephirosu** [comment]
Fixed.Made parent component "Middle text" where i put PromoMessage where via props using Message made text in middle of navbar.
