### ISSUE TITLE
Number of guests not working as expected

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#15]
<img width="951" alt="Screenshot 2024-07-30 at 2 03 47 PM" src="https://github.com/user-attachments/assets/400dbacb-ae58-46e4-9cae-7516ed4d98a3">

When I try to increment one of these parameters, dropdown get's closed so I am not able to interact with it at all.

**Comment by Sephirosu** [comment]
Fixed.Modal-content added in div that wrap component.
