### ISSUE TITLE
Mobile modals update

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#18]
<img width="392" alt="Screenshot 2024-07-30 at 2 20 49 PM" src="https://github.com/user-attachments/assets/2dea09cc-2ec4-4418-a60e-2961b5ebc03f">

Once user opens up this modal, we have a couple of options here to select from: Location, check in, check out and number of guests

<img width="396" alt="Screenshot 2024-07-30 at 2 20 53 PM" src="https://github.com/user-attachments/assets/582fd3a0-4aab-49e5-810b-e17dad96259f">
<img width="399" alt="Screenshot 2024-07-30 at 2 20 59 PM" src="https://github.com/user-attachments/assets/ba5fb0fa-2d19-47fb-b5b9-ad9fe5911d43">

Looking at these two screenshots we have two problems:
1. We don't know with which field we're interacting, is it check-in or check-out? We need to add some labels so the user knows.
2. We have "X/close" button but we should have "Back" button. Same as it's on the "Number of guests" screen.

<img width="399" alt="Screenshot 2024-07-30 at 2 21 05 PM" src="https://github.com/user-attachments/assets/4b86e041-9c6b-4994-925b-e27b6cb430e8">

**Comment by Sephirosu** [comment]
In collaboration with UI designer, I changed arrows position and put them around month.Also i added {title section} Check-in and Check-out so you can see are you checkin in or out.
