### ISSUE TITLE
Apartment slider not working

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#19]
<img width="311" alt="Screenshot 2024-07-30 at 2 25 15 PM" src="https://github.com/user-attachments/assets/f7ecde40-4437-47eb-abeb-467ff6679118">

These bullets at the bottom of the image should be indicators for the different images of the apartments which should be able to slide, left or right.

Currently, this slider is not working.

**Comment by Sephirosu** [comment]
Fixed.
