### ISSUE TITLE
Format currency as expected ( best practice )

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#23]
https://github.com/Sephirosu/figma-next-tailwind/blob/5c2265816c9ba4c67ab547a2f2959df413e0d4d8/src/components/Property/MoreAdditionalInfo.tsx#L22-L23

How to format currency format https://www.freecodecamp.org/news/how-to-format-number-as-currency-in-javascript-one-line-of-code/

**Comment by Sephirosu** [comment]
i make new component currency formatter and passed props in available price.I put usdt currency.
