### ISSUE TITLE
Make the data part of the apartment JSON

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#24]
https://github.com/Sephirosu/figma-next-tailwind/blob/5c2265816c9ba4c67ab547a2f2959df413e0d4d8/src/components/Property/AdditionalInfo.tsx#L17-L20

Rating data should be also part of the JSON for each apartment.

**Comment by Sephirosu** [comment]
I made new component rating where i put faStar and Rating that i already made in json.Changed first price cause of test.
