### ISSUE TITLE
Component should be part of the layout.tsx file and not included within the root page itself

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#6]
https://github.com/Sephirosu/figma-next-tailwind/blob/5c2265816c9ba4c67ab547a2f2959df413e0d4d8/src/app/page.tsx#L10

The navbar component is the component that should be reused throughout all pages, the same as the footer, that's why it belongs inside the **layout.tsx** page.

**Reference: ** https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts

**Comment by Sephirosu** [comment]
fixed.Navbar and Footer inside Layout
