### ISSUE TITLE
public/icons generate as svgr/react icons

### ISSUE THREAD

**Issue by mSenad** [Sephirosu/figma-next-tailwind#8]
**Folder: **/public/icons****

- Hajmo sve ove ikone sada da prebacimo u react ikonice. Koristi ovo https://react-svgr.com/
- Ovaj servis se koristi da pretvori sve .svg ikonice u .jsx komponente koje mozes kasnije da koristis.
- Ima pristup za NextJS aplikacije

**Comment by Sephirosu** [comment]
Konfigurisano.Sada imam pristup ubacivanju svakog svg kao react ikonicu sto automatski brise width,height,alt i src kao i importovanje Image osim ako nije png fajl.
Dodao pathove sa "@" da je lakse naci,a i napisati.
Primjer import Frame from "@icons/frame2.svg"; 
Dodao path i za ostale foldere.
